version: "3"

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - database:/app/database
    environment:
      - FLASK_ENV=development
      - POSTGRES_HOST=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    depends_on:
      database:
        condition: service_healthy
    networks:
      - dataai

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      
    container_name: react_ui
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    networks:
      - dataai
    command: ["npm", "start"]

  database:
    container_name: database
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - dataai
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 3s


networks:
  dataai:

volumes:
  database:


